### ISSUE TITLE
Deepcore Inaccurate Max Ammo

### ISSUE THREAD

**Issue by xChristiano** [drg-tools/karl.gg#189]
In karl.gg, base Deepcore 40MM PGL has 8 max ammo. However on the wiki, it says the base has 9 max ammo. Please fix :C

**Comment by phg49389** [comment]
This is a conflict between what the game displays to the player and what it actually tracks internally. Technically, PGL does only have `AmmoDrivenWeapon.AmmoCount = 8` and `AmmoDrivenWeapon.ClipCount = 1`, but what gets displayed on the weapon model is a flat 9 and it seems the Wiki team has mirrored that. The ingame model *used* to say 1+8, but Update 32.0 included this as one of its patch notes:

"Made the Max Ammo stat include the round in the launcher since there is no magazine size stat for this weapon"

So, this is less of bug on Karl.gg and more of a different way to view the information. I'll leave it to the Karl.gg devs on how they want to handle this.

**Comment by phg49389** [comment]
From a Slack thread:

My recommendation is to change Karl.gg to display Engineer's PGL Max Ammo stat as 9 (+2/+3/+2/+4/-2/x0.3 depending on mods and Overclocks) so that it matches up with the in-game Max Ammo stat in Equipment Terminal as well as on the physical model. This would be to make it as easy as possible for users of the website to create their loadouts without having to do any "translation" of the stats between what they see in-game and what gets displayed on the website.

As for the DPS Calculator, I'm choosing to keep the PGL displaying 1+8 on the PGL because it's designed to be a highly technical in-depth overview of the weapon, and I want to reveal the underlying stat changes to users so that it's less obscured how the metrics get calculated.

**Comment by Darthmaul** [comment]
Hello @xChristiano ,

We've had a chance to discuss this internally. Based on the feedback from Phil, we have decided to mark this as "wont' fix". Technically the value is correct in conjunction with the "Clip Size" data point, but the Game & Wiki have chosen to represent that as a combined number. For us, this is actually a significant effort to make this change -- a problem of technical debt we are working to remediate.

We have decided to prioritize a few other milestones which will make it easier to implement adjustments like this in the future.

Thanks for your report. Please continue to let us know if other issues arise.
