### ISSUE TITLE
Translation in other languages

### ISSUE THREAD

**Issue by spawn900** [drg-tools/karl.gg#199]
What about translating the page in other languages?

**Comment by Darthmaul** [comment]
Howdy @spawn900 , thanks for requesting this feature. You are not the first one to suggest this either. I'm guessing you would be requesting German (based on your profile)? 

I was wondering, have you tried using your browser to translate our site? There are a variety of options which would allow you to translate the site browser-side, rather than through our application itself.  Chrome, for example: https://support.google.com/chrome/answer/173424?co=GENIE.Platform%3DDesktop&hl=en

If you have tried that, I would definitely be interested in the results.

This would be a large request for us to fulfill, and we may not even be able to deliver more value than your browser can with a simple add-on(or out of the box).

Curious your thoughts.
