### ISSUE TITLE
See more advanced stats - Error 404

### ISSUE THREAD

**Issue by Yaryujin** [drg-tools/karl.gg#373]
Selecting any mods for the **Nishanka Boltshark X-80** and clicking on **See more advanced stats** opens this URL "https://karl.gg/asv/24/ABAAB-"

**Comment by Darthmaul** [comment]
Sorry for the delay in getting back to you on this. Our Advance Stats view has been broken on some of the newer content for a while, this is due to the fact that we haven't yet compiled the data for these newer weapons. It's a manual process that our friend Meatshield has to do in his free time, and once he has a chance to dedicate some time to this we will work to merge that data in. 

We are tracking this bug here: https://github.com/drg-tools/karl.gg/issues/312

Meatshield has been focused on some other data aspects for the site, and the ASV item is lower in the priority. Hoping to prioritize those updates sometime later this year. Appreciate you reaching out, and please feel free to add further feedback on the issue above. Thanks
